SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [P_DDO_REG_DETAILS_READ_BY_STATUS]
	@STATUS BIT = NULL
AS
BEGIN TRY
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

	IF @STATUS IS NULL
	BEGIN
		SELECT 
		   REG_ID
		  ,DDO_REGISTRATION.DDO_CODE
		  ,DDO_MASTER.DDO_NAME 
		  ,DDO_REGISTRATION.DEPT_ID
		  ,DEPT_MASTER.DEPT_NAME
		  ,DDO_REGISTRATION.DISTRICT_ID
		  ,DISTRICT_MASTER.DISTRICT_NAME
		  ,DDO_REGISTRATION.DESIG_ID
		  ,DESIG_MASTER.DESIG_DESC
		  ,UPPER(DDO_REGISTRATION.OFFICE_ADD_1)	AS OFFICE_ADD_1			
		  ,UPPER(DDO_REGISTRATION.OFFICE_ADD_2)	AS OFFICE_ADD_2					
		  ,UPPER(DDO_REGISTRATION.TIN_NO)		AS TIN_NO							
		  ,UPPER(DDO_REGISTRATION.TAN_NO)		AS TAN_NO						
		  ,LOWER(DDO_REGISTRATION.EMAIL)		AS EMAIL						
		  ,UPPER(DDO_REGISTRATION.CONTACT_N0)	AS CONTACT_N0
		  ,DDO_REGISTRATION.CUR_STATUS			AS CUR_STATUS
		  ,CASE 
				WHEN DDO_REGISTRATION.CUR_STATUS = 0 THEN 'PENDING'
				ELSE 'APPROVED'	
		   END									AS [STATUS_NAME]
		  ,DDO_REGISTRATION.ENTRY_TIME			AS ENTRY_TIME
		  ,DDO_REGISTRATION.PASSED_BY
		  ,DDO_REGISTRATION.PASSING_TIME
		FROM DDO_REGISTRATION 
			LEFT JOIN DDO_MASTER
				ON DDO_REGISTRATION.DDO_CODE = DDO_MASTER.DDO_CODE
			LEFT JOIN DEPT_MASTER 
				ON DDO_REGISTRATION.DEPT_ID = DEPT_MASTER.DEPT_ID
			LEFT JOIN DESIG_MASTER 
				ON DDO_REGISTRATION.DESIG_ID = DESIG_MASTER.DESIG_ID
			LEFT JOIN DISTRICT_MASTER 
				ON DDO_REGISTRATION.DISTRICT_ID = DISTRICT_MASTER.DISTRICT_ID
	END
	ELSE
	BEGIN
		SELECT 
		   REG_ID
		  ,DDO_REGISTRATION.DDO_CODE
		  ,DDO_MASTER.DDO_NAME 
		  ,DDO_REGISTRATION.DEPT_ID
		  ,DEPT_MASTER.DEPT_NAME
		  ,DDO_REGISTRATION.DISTRICT_ID
		  ,DISTRICT_MASTER.DISTRICT_NAME
		  ,DDO_REGISTRATION.DESIG_ID
		  ,DESIG_MASTER.DESIG_DESC
		  ,UPPER(DDO_REGISTRATION.OFFICE_ADD_1)	AS OFFICE_ADD_1			
		  ,UPPER(DDO_REGISTRATION.OFFICE_ADD_2)	AS OFFICE_ADD_2					
		  ,UPPER(DDO_REGISTRATION.TIN_NO)		AS TIN_NO							
		  ,UPPER(DDO_REGISTRATION.TAN_NO)		AS TAN_NO						
		  ,LOWER(DDO_REGISTRATION.EMAIL)		AS EMAIL						
		  ,UPPER(DDO_REGISTRATION.CONTACT_N0)	AS CONTACT_N0
		  ,DDO_REGISTRATION.CUR_STATUS			AS CUR_STATUS
		  ,CASE 
				WHEN DDO_REGISTRATION.CUR_STATUS = 0 THEN 'PENDING'
				ELSE 'APPROVED'	
		   END									AS [STATUS_NAME]
		  ,DDO_REGISTRATION.ENTRY_TIME			AS ENTRY_TIME
		  ,DDO_REGISTRATION.PASSED_BY
		  ,DDO_REGISTRATION.PASSING_TIME
		FROM DDO_REGISTRATION 
			LEFT JOIN DDO_MASTER
				ON DDO_REGISTRATION.DDO_CODE = DDO_MASTER.DDO_CODE
			LEFT JOIN DEPT_MASTER 
				ON DDO_REGISTRATION.DEPT_ID = DEPT_MASTER.DEPT_ID
			LEFT JOIN DESIG_MASTER 
				ON DDO_REGISTRATION.DESIG_ID = DESIG_MASTER.DESIG_ID
			LEFT JOIN DISTRICT_MASTER 
				ON DDO_REGISTRATION.DISTRICT_ID = DISTRICT_MASTER.DISTRICT_ID
		WHERE DDO_REGISTRATION.CUR_STATUS = @STATUS
	END
END TRY 


BEGIN CATCH
	DECLARE @ERR  VARCHAR(1000)
	SELECT @ERR=ERROR_MESSAGE()
	IF	ERROR_SEVERITY () > 12
		BEGIN
			RAISERROR (@ERR, 16, 20)
		END
		--
		ELSE
		--
		BEGIN
			RAISERROR (@ERR, 12, 2)
		END
END CATCH