SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

DROP PROCEDURE IF EXISTS P_READ_DDO_DETAILS
GO

CREATE PROCEDURE [dbo].[P_READ_DDO_DETAILS]
(
	@DDO_CODE VARCHAR(6)
)

AS

BEGIN TRY
	
	SELECT 
		DDM.DDO_ID,
		DDM.DEPT_ID,
		DDM.DDO_CODE,
		DDM.DDO_NAME,
		DDM.DESIG_ID,
		DESM.DESIG_DESC,
		DDM.DISTRICT_ID,
		DISM.DISTRICT_NAME
	FROM 
		DDO_MASTER DDM 
			LEFT OUTER JOIN DESIG_MASTER DESM 
				ON DDM.DESIG_ID = DESM.DESIG_ID 
			LEFT OUTER JOIN DISTRICT_MASTER DISM 
				ON DDM.DISTRICT_ID = DISM.DISTRICT_ID 
	WHERE DDM.DDO_CODE= @DDO_CODE

END TRY 


BEGIN CATCH
	DECLARE @ERR  VARCHAR(1000)
	SELECT @ERR=ERROR_MESSAGE()
	IF	ERROR_SEVERITY () > 12
		BEGIN
			RAISERROR (@ERR, 16, 20)
		END
		--
		ELSE
		--
		BEGIN
			RAISERROR (@ERR, 12, 2)
		END
END CATCH

GO