IF NOT EXISTS(SELECT OBJECT_ID FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID('RCO_Registration') AND NAME = 'REG_ID')
BEGIN
	ALTER TABLE RCO_Registration ADD REG_ID BIGINT IDENTITY
	PRINT 'REG_ID COLUMN CREATED ON RCO_Registration'
END
GO

IF NOT EXISTS(SELECT OBJECT_ID FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID('RCO_Registration') AND NAME = 'CUR_STATUS')
BEGIN
	ALTER TABLE RCO_Registration ADD CUR_STATUS BIT NOT NULL DEFAULT 0
	PRINT 'CUR_STATUS COLUMN CREATED ON RCO_Registration'
END
GO

IF NOT EXISTS(SELECT OBJECT_ID FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID('RCO_Registration') AND NAME = 'PASSED_BY')
BEGIN
	ALTER TABLE RCO_Registration ADD PASSED_BY INT NULL
	PRINT 'PASSED_BY COLUMN CREATED ON RCO_Registration'
END
GO

IF NOT EXISTS(SELECT OBJECT_ID FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID('RCO_Registration') AND NAME = 'PASSING_TIME')
BEGIN
	ALTER TABLE RCO_Registration ADD PASSING_TIME DATETIME NULL
	PRINT 'PASSED_TIME COLUMN CREATED ON RCO_Registration'
END
GO